#!/bin/bash      
#title           : Install Maven Build Tool
#description     : Execute this script as root user
#author		     : Mthun Technologies
#date            : 08112012
#version         : 1.0    
#usage		     : sh mavenInstallation.sh
#CopyRights      : Mithun Technologies
#Contact         : 9980923226 | devopstrainingblr@gmail.com


echo 'Maven Installation started.'
echo '---------------------------'
yum install wget zip unzip -y
cd /opt
wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
unzip apache-maven-3.6.3.zip
echo "export M2_HOME=/opt/apache-maven-3.6.0" >> ~/.bash_profile
#To set the varibales in System wide environment , use below file
#echo "export M2_HOME=/opt/apache-maven-3.6.0" >> /etc/profile

echo 'export PATH=$PATH:$M2_HOME/bin' >> ~/.bash_profile
source ~/.bash_profile

echo 'Maven Installation done.'
echo '-----------------------'

mvn -version
