#!/bin/bash

echo "Nexus Installation Started"

sudo yum install wget tar -y

cd /opt

sudo wget https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/nexus-3.19.1-01-unix.tar.gz
sudo wget http://download.sonatype.com/nexus/3/nexus-3.16.0-01-unix.tar.gz

sudo tar -zxvf nexus-3.19.1-01-unix.tar.gz

sudo mv nexus-3.19.1-01-unix.tar.gz nexus3

sudo useradd nexus
sudo visudo
	nexus ALL=(ALL) NOPASSWD:ALL

sudo chown -R nexus:nexus /opt/nexus3
sudo chown -R nexus:nexus /opt/sonatype-work

chmod -R 775 /opt/nexus3
chmod -R 775 /opt/sonatype-work/

sudo vi /opt/nexus3/bin/nexus.rc
run_as_user="nexus"
sudo ln -s /opt/nexus3/bin/nexus /etc/init.d/nexus3

sudo su - nexus

sudo systemctl enable nexus

sudo systemctl start nexus

echo "Nexus Installation Completed"

